export const GET_ALL_POST_BOOKMARK = "GET_ALL_POST_BOOKMARK";
export const SET_ALL_POST_BOOKMARK = "SET_ALL_POST_BOOKMARK";
export const ADD_POST_BOOKMARK = "ADD_POST_BOOKMARK";
export const DELETE_POST_BOOKMARK = "DELETE_POST_BOOKMARK";
export const IS_BOOKMARK = "IS_BOOKMARK";
